name: scheduler
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.3
  crypto: ^3.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.6
  freezed_annotation: ^2.2.0
  get: ^4.6.5
  google_fonts: any
  intl: ^0.18.0
  json_annotation: ^4.8.1
  path: ^1.8.3
  pull_to_refresh: ^2.0.0
  shimmer: ^3.0.0
  sqflite: ^2.2.8+4

dev_dependencies:
  build_runner: any
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: any
  json_serializable: any

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/png/onboarding/
    - assets/example.db
