name: scheduler
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.3
  crypto: ^3.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_sticky_header: ^0.6.5
  flutter_svg: ^2.0.6
  flutter_swipe_action_cell: ^3.1.1
  freezed_annotation: ^2.2.0
  get: ^4.6.5
  get_storage: ^2.1.1
  google_fonts: any
  image_picker: ^0.8.7+5
  intl: ^0.18.0
  json_annotation: ^4.8.1
  path: ^1.8.3
  path_provider: ^2.0.15
  pull_to_refresh: ^2.0.0
  shimmer: ^3.0.0
  sqflite: ^2.2.8+4
  table_calendar: ^3.0.9
  url_launcher: ^6.1.11

dev_dependencies:
  build_runner: any
  flutter_lints: any
  flutter_native_splash: any
  flutter_test:
    sdk: flutter
  freezed: any
  icons_launcher: any
  json_serializable: any

icons_launcher:
  image_path: "assets/app_icon.jpeg"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/svg/Regular/
    - assets/png/onboarding/
    - assets/png/home/
    - assets/example.db
