name: scheduler
description: A new Flutter project.
publish_to: 'none'

version: 0.3.8+0.0.28

environment:
  sdk: '>=3.4.3'

dependencies:
  archive: ^3.6.1
  audio_service: ^0.18.12
  audio_session: ^0.1.18
  auto_size_text: ^3.0.0
  bitsdojo_window: ^0.1.6
  cached_network_image: ^3.3.1
  camera: ^0.11.0+2
  collection: any
  crypto: ^3.0.3
  csv: ^6.0.0
  device_info_plus: ^10.1.2
  dio: ^5.3.3
  dotted_border: ^2.0.0+3
  drift: ^2.19.1+1
  drift_flutter: ^0.1.0
  firebase_analytics: ^11.2.1
  firebase_core: ^3.3.0
  firebase_crashlytics: ^4.0.4
  flutter:
    sdk: flutter
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.15
  flutter_local_notifications: ^17.2.2
  flutter_localizations:
    sdk: flutter
  flutter_sticky_header: ^0.6.5
  flutter_svg: ^2.0.6
  flutter_swipe_action_cell: ^3.1.1
  freezed_annotation: ^2.2.0
  geolocator: ^12.0.0
  get: ^4.6.5
  get_storage: ^2.1.1
  google_fonts: any
  google_generative_ai: ^0.4.4
  google_mlkit_barcode_scanning: ^0.12.0
  google_mlkit_commons: ^0.7.1
  google_mlkit_object_detection: ^0.13.0
  google_mlkit_text_recognition: ^0.13.0
  http: ^1.1.0
  image: ^4.0.17
  image_cropper: ^8.0.1
  image_picker: ^1.0.7
  intl: any
  json_annotation: ^4.8.1
  just_audio: ^0.9.35
  metadata_god: ^0.5.2+1
  mime: ^1.0.4
  package_info_plus: ^8.0.2
  path: ^1.8.3
  path_provider: ^2.1.1
  percent_indicator: ^4.2.3
  permission_handler: any
  photo_gallery: ^2.1.1
  photo_view: ^0.15.0
  pie_chart: ^5.3.2
  pull_to_refresh: ^2.0.0
  qr_image: ^1.0.0
  rxdart: ^0.27.7
  share_plus: ^10.0.0
  shimmer: ^3.0.0
  sqflite: ^2.2.8+4
  syncfusion_flutter_xlsio: ^26.2.9
  table_calendar: ^3.0.9
  timezone: ^0.9.2
  url_launcher: ^6.1.11
  uuid: ^3.0.7
  win32: ^5.5.4

dev_dependencies:
  build_runner: any
  drift_dev: ^2.19.0
  flutter_lints: any
  flutter_native_splash: any
  flutter_test:
    sdk: flutter
  freezed: any
  icons_launcher: any
  json_serializable: any

icons_launcher:
  image_path: "assets/png/appIcons/app_icon.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/svg/Regular/
    - assets/png/onboarding/
    - assets/png/home/
    - assets/png/appIcons/
    - assets/png/weather/small/
    - assets/png/weather/large/
    - assets/png/ekyc/
