name: scheduler
description: A new Flutter project.
publish_to: 'none'
version: 0.3.4+0.0.12

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.3
  collection: any
  crypto: ^3.0.3
  device_info_plus: ^9.0.2
  dotted_border: ^2.0.0+3
  firebase_analytics: ^10.4.4
  firebase_core: ^2.15.0
  firebase_crashlytics: ^3.3.4
  flutter:
    sdk: flutter
  flutter_local_notifications: ^14.1.1
  flutter_localizations:
    sdk: flutter
  flutter_sticky_header: ^0.6.5
  flutter_svg: ^2.0.6
  flutter_swipe_action_cell: ^3.1.1
  freezed_annotation: ^2.2.0
  geolocator: ^9.0.2
  get: ^4.6.5
  get_storage: ^2.1.1
  google_fonts: any
  image_picker: ^0.8.7+5
  intl: ^0.18.0
  json_annotation: ^4.8.1
  package_info_plus: ^4.0.2
  path: ^1.8.3
  path_provider: ^2.0.15
  pie_chart: ^5.3.2
  pull_to_refresh: ^2.0.0
  share_plus: ^7.0.2
  shimmer: ^3.0.0
  sqflite: ^2.2.8+4
  syncfusion_flutter_xlsio: ^22.2.5
  table_calendar: ^3.0.9
  timezone: ^0.9.2
  url_launcher: ^6.1.11

dev_dependencies:
  build_runner: any
  flutter_lints: any
  flutter_native_splash: any
  flutter_test:
    sdk: flutter
  freezed: any
  icons_launcher: any
  json_serializable: any

icons_launcher:
  image_path: "assets/png/appIcons/app_icon.jpg"
platforms:
  android:
    enable: true
  ios:
    enable: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/svg/Regular/
    - assets/png/onboarding/
    - assets/png/home/
    - assets/png/appIcons/
    - assets/png/weather/small/
    - assets/png/weather/large/
