name: aio
description: A new Flutter project.
publish_to: 'none'

version: 0.3.12+06.24.2025

environment:
  sdk: '>=3.6.0'

dependencies:
  archive: any
  auto_size_text: any
  cached_network_image: any
  camera: any
  collection: any
  crypto: any
  csv: any
  device_info_plus: any
  dio: any
  dotted_border: any
  drift: any
  drift_flutter: any
  file_picker: any
  firebase_ai: any
  firebase_analytics: any
  firebase_core: any
  firebase_crashlytics: any
  flutter:
    sdk: flutter
  flutter_local_notifications: any
  flutter_localizations:
    sdk: flutter
  flutter_sticky_header: any
  flutter_svg: any
  flutter_swipe_action_cell: any
  freezed_annotation: any
  full_calender: ^1.2.12
  geolocator: any
  get: any
  get_storage: any
  google_fonts: any
  http: any
  image: any
  image_cropper: any
  image_picker: any
  intl: any
  json_annotation: any
  just_audio: any
  mime: any
  package_info_plus: any
  path: any
  path_provider: any
  percent_indicator: any
  permission_handler: any
  photo_gallery: any
  photo_view: any
  pie_chart: any
  pull_to_refresh: any
  qr_image: any
  rxdart: any
  share_plus: any
  shimmer: any
  skeletonizer: any
  sqflite: any
  super_clipboard: any
  syncfusion_flutter_xlsio: any
  table_calendar: any
  timezone: any
  url_launcher: any

dev_dependencies:
  build_runner: any
  drift_dev: ^2.19.0
  flutter_lints: any
  flutter_native_splash: any
  flutter_test:
    sdk: flutter
  freezed: any
  icons_launcher: any
  json_serializable: any

icons_launcher:
  image_path: "assets/png/appIcons/app_icon.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/svg/Regular/
    - assets/png/onboarding/
    - assets/png/home/
    - assets/png/appIcons/
    - assets/png/weather/small/
    - assets/png/weather/large/
    - assets/png/ekyc/
