// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzQvFCiVNHGjTyDdgaIRTwCtmVa0hgTU0',
    appId: '1:911452778918:web:62f77d63ae0e7552cc5f67',
    messagingSenderId: '911452778918',
    projectId: 'tools-a75c2',
    authDomain: 'tools-a75c2.firebaseapp.com',
    storageBucket: 'tools-a75c2.appspot.com',
    measurementId: 'G-R4LZWVKY72',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBqjAupE1gVggrpIEc1blNckOsHqx4uQY',
    appId: '1:289109535313:android:c7986ee8397becbb6c6670',
    messagingSenderId: '289109535313',
    projectId: 'allinone-71666',
    storageBucket: 'allinone-71666.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHN9fmcFz4pJD8g3Hnihe0PjASbzihcZs',
    appId: '1:289109535313:ios:1cefb9f44bbd01f06c6670',
    messagingSenderId: '289109535313',
    projectId: 'allinone-71666',
    storageBucket: 'allinone-71666.firebasestorage.app',
    iosBundleId: 'com.lgcns.testApp.aio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEAfKyQo_gue9K9IfQhf5Nxz9l_VnfiPs',
    appId: '1:911452778918:ios:08f09e570ce2cb8dcc5f67',
    messagingSenderId: '911452778918',
    projectId: 'tools-a75c2',
    storageBucket: 'tools-a75c2.appspot.com',
    iosBundleId: 'com.example.aio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzQvFCiVNHGjTyDdgaIRTwCtmVa0hgTU0',
    appId: '1:911452778918:web:4e44a70d79e5a668cc5f67',
    messagingSenderId: '911452778918',
    projectId: 'tools-a75c2',
    authDomain: 'tools-a75c2.firebaseapp.com',
    storageBucket: 'tools-a75c2.appspot.com',
    measurementId: 'G-14ZB02CKBE',
  );
}